### ISSUE TITLE
How can I download the model weight?

### ISSUE THREAD

**Issue by FanqingM** [AlaaLab/InstructCV#8]
It seems that use checkpoint link in readme.md cannot download the weight

**Comment by sunrainyg** [comment]
Hi,

You can use our HF model at https://huggingface.co/alaa-lab/InstructCV, or download the checkpoint from this link: https://pan.baidu.com/s/1xZgaTMXvrTkPXWGYdd7aJw?pwd=44sz; Password: 44sz. I recommend using the HF model, as this checkpoint is not the latest one.

The latest checkpoint will be uploaded in about 2 weeks due to some server problems. Let me know if you have further questions.
